# Generated by Django 3.2.15 on 2022-08-30 09:54

import django.core.validators
from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название ингредиента')),
                ('measurement_unit', models.CharField(choices=[('г', 'грамм'), ('горсть', 'горсть'), ('доль.', 'долька'), ('зв.', 'звездочка'), ('зуб.', 'зубчик'), ('кап.', 'капля'), ('кг', 'килограмм'), ('кус.', 'кусок'), ('л', 'литр'), ('лист', 'лист'), ('мл', 'миллилитр'), ('пак.', 'пакетик'), ('пач.', 'пачка'), ('пласт', 'пласт'), ('по вкусу', 'по вкусу'), ('пуч.', 'пучок'), ('ст.', 'стакан'), ('ст.л.', 'столовая ложка'), ('стеб.', 'стебель'), ('стр.', 'стручок'), ('туш.', 'тушка'), ('уп.', 'упаковка'), ('ч.л.', 'чайная ложка'), ('шт.', 'штук'), ('щеп.', 'щепотка')], max_length=200, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество единиц ингредиента должно быть не менее 1!')])),
            ],
            options={
                'verbose_name': 'Количество ингредиента',
                'verbose_name_plural': 'Количество ингредиентов',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='recipes/', verbose_name='Изображение')),
                ('text', models.TextField(verbose_name='Описание')),
                ('cooking_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время приготовления не может быть меньше 1 минуты')], verbose_name='Время приготовления')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('color', models.CharField(choices=[('#ff0000', 'Красный'), ('#ffa500', 'Оранжевый'), ('#ffff00', 'Жёлтый'), ('#008000', 'Зелёный'), ('#0000ff', 'Голубой'), ('#4b0082', 'Синий'), ('#ee82ee', 'Фиолетовый'), ('null', 'Бесцветный')], max_length=7, verbose_name='Цвет в HEX')),
                ('slug', models.SlugField(max_length=200, unique=True, validators=[recipes.validators.LatinAlphabetNumberValidator], verbose_name='Уникальный слаг')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['-id'],
            },
        ),
    ]
